const HardcodeZara = [
  {
    title: "Nike",
    description: "Nike Sportswear Futura Luxe",
    image: "../assets/p1.png",
    price: 1300,
    beforePrice: 1500,
    category: "Bag",
    rating: 4,
    id: 0,
  },
  {
    title: "Adidas",
    description: "Adidas Sportswear Futura",
    image: "../assets/p1.png",
    price: 1400,
    beforePrice: 1700,
    category: "Bag",
    rating: 4,
    id: 1,
  },
  {
    title: "Puma",
    description: "Puma Sportswear Futura Luxe",
    image: "../assets/p1.png",
    price: 1500,
    beforePrice: "",
    category: "Bag",
    rating: 4,
    id: 2,
  },
  {
    title: "fila",
    description: "fila Sportswear Futura Luxe",
    image: "../assets/p1.png",
    price: 1600,
    beforePrice: "",
    category: "Bag",
    rating: 4,
    id: 3,
  },
];
export default HardcodeZara;
